manutask/administracao/urls.py
from django.urls import path
from .views import IndexTemplateView, PessoaListView, PessoaCreateView, PessoaUpdateView, \
    PessoaDeleteView, ImovelListView, ImovelUpdateView, ImovelDeleteView, ImovelCreateView, \
    OficinaListView, OficinaUpdateView, OficinaDeleteView, OficinaCreateView, \
    OrdemServicoListView, OrdemServicoUpdateView, OrdemServicoDeleteView, OrdemServicoCreateView

app_name = 'administracao'

urlpatterns = [
    # Homepage
    path('', IndexTemplateView.as_view(), name='index'),

    # Pessoas
    path('pessoas/', PessoaListView.as_view(), name='lista_pessoas'),
    path('pessoa/atualiza/<pk>', PessoaUpdateView.as_view(), name='atualiza_pessoa'),
    path('pessoa/excluir/<pk>', PessoaDeleteView.as_view(), name='deleta_pessoa'),
    path('pessoa/cadastrar', PessoaCreateView.as_view(), name='cadastra_pessoa'),

    # Imoveis
    path('imoveis/', ImovelListView.as_view(), name='lista_imoveis'),
    path('imovel/atualiza/<pk>', ImovelUpdateView.as_view(), name='atualiza_imovel'),
    path('imovel/excluir/<pk>', ImovelDeleteView.as_view(), name='deleta_imovel'),
    path('imovel/cadastrar', ImovelCreateView.as_view(), name='cadastra_imovel'),

    # Oficinas
    path('oficinas/', OficinaListView.as_view(), name='lista_oficinas'),
    path('oficina/atualiza/<pk>', OficinaUpdateView.as_view(), name='atualiza_oficina'),
    path('oficina/excluir/<pk>', OficinaDeleteView.as_view(), name='deleta_oficina'),
    path('oficina/cadastrar', OficinaCreateView.as_view(), name='cadastra_oficina'),

    # Ordens de Serviço
    path('os/', OrdemServicoListView.as_view(), name='lista_os'),
    path('os/atualiza/<pk>', OrdemServicoUpdateView.as_view(), name='atualiza_os'),
    path('os/excluir/<pk>', OrdemServicoDeleteView.as_view(), name='deleta_os'),
    path('os/cadastrar', OrdemServicoCreateView.as_view(), name='cadastra_os'),
]

manutask/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('administracao.urls', namespace='administracao')),
    # Interface administrativa
    path('admin/', admin.site.urls),
]

manutask/administracao/models.py
from django.db import models
from datetime import datetime
# from django import forms


# Entidades do sistema
class Pessoa(models.Model):
    cpf = models.CharField(max_length=11)
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=100)

    def __repr__(self):
        return f'{self.nome} {self.sobrenome}'

    def __str__(self):
        return f'{self.nome} {self.sobrenome}'


class Oficina(models.Model):
    id_supervisor = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE
    )
    nome = models.CharField(max_length=20)

    def __repr__(self):
        return f'{self.nome}'

    def __str__(self):
        return f'{self.nome}'


class Imovel(models.Model):
    id_locador = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE
    )
    rua = models.CharField(max_length=50)
    numero = models.IntegerField()
    latitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        null=True
    )
    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        null=True
    )

    def __repr__(self):
        return f'{self.rua}, {self.numero}'

    def __str__(self):
        return f'{self.rua}, {self.numero}'


class OrdemServico(models.Model):
    id_reclamante = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE,
        null=False,
        related_name='reclamante'
    )
    id_imovel = models.ForeignKey(
        Imovel,
        on_delete=models.CASCADE,
        null=False
    )
    timestamp_abertura = models.DateTimeField(
        default=datetime.now()
    )
    id_oficina_responsavel = models.ForeignKey(
        Oficina,
        on_delete=models.CASCADE,
        null=True
    )
    descricao_problema = models.TextField(max_length=255, null=False)
    timestamp_solucao = models.DateTimeField(null=True)
    descricao_solucao = models.TextField(max_length=255, null=True)
    id_solucionador = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE,
        related_name='solucionador',
        null=True
    )

manutask/administracao/forms.py
from django import forms
from .models import Pessoa, Imovel, Oficina, OrdemServico


class CadastraPessoaForm(forms.ModelForm):

    class Meta:
        model = Pessoa
        fields = '__all__'
        labels = {
            'nome': 'Nome',
            'sobrenome': 'Sobrenome',
            'cpf': 'CPF',
        }


class CadastraImovelForm(forms.ModelForm):

    class Meta:
        model = Imovel
        fields = '__all__'
        labels = {
            'id_locador': 'Locador',
            'rua': 'Rua',
            'numero': 'Número',
            'latitude': 'Latitude',
            'longitude': 'Longitude',
        }


class CadastraOficinaForm(forms.ModelForm):

    class Meta:
        model = Oficina
        fields = '__all__'
        labels = {
            'id_supervisor': 'Supervisor',
            'nome': 'Nome',
        }


class CadastraOrdemServicoForm(forms.ModelForm):

    class Meta:
        model = OrdemServico
        fields = '__all__'
        exclude = [
            'timestamp_abertura',
            'timestamp_solucao',
            'descricao_solucao',
            'id_solucionador',
        ]
        labels = {
            'id_reclamante': 'Aberta por',
            'id_imovel': 'Imóvel afetado',
            'id_oficina_responsavel': 'Tipo de serviço',
            'descricao_problema': 'Descrição do problema',
        }

manutask/administracao/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, \
    DeleteView
from .models import Pessoa, Imovel, Oficina, OrdemServico
from .forms import CadastraPessoaForm, CadastraImovelForm, CadastraOficinaForm, \
    CadastraOrdemServicoForm


# View da Homepage
class IndexTemplateView(TemplateView):
    template_name = 'administracao/index.html'


# Views da entidade Pessoa
class PessoaListView(ListView):
    template_name = 'administracao/pessoa/listapessoas.html'
    model = Pessoa
    context_object_name = 'pessoas'


class PessoaUpdateView(UpdateView):
    template_name = 'administracao/pessoa/atualizapessoa.html'
    model = Pessoa
    fields = '__all__'
    context_object_name = 'pessoa'
    success_url = reverse_lazy('administracao:lista_pessoas')


class PessoaDeleteView(DeleteView):
    template_name = 'administracao/pessoa/deletapessoa.html'
    model = Pessoa
    context_object_name = 'pessoa'
    success_url = reverse_lazy('administracao:lista_pessoas')


class PessoaCreateView(CreateView):
    template_name = 'administracao/pessoa/cadastrapessoa.html'
    model = Pessoa
    form_class = CadastraPessoaForm
    success_url = reverse_lazy('administracao:lista_pessoas')


# Views da entidade Imoveis
class ImovelListView(ListView):
    template_name = 'administracao/imovel/listaimoveis.html'
    model = Imovel
    context_object_name = 'imoveis'


class ImovelUpdateView(UpdateView):
    template_name = 'administracao/imovel/atualizaimovel.html'
    model = Imovel
    fields = '__all__'
    context_object_name = 'imovel'
    success_url = reverse_lazy('administracao:lista_imoveis')


class ImovelDeleteView(DeleteView):
    template_name = 'administracao/imovel/deletaimovel.html'
    model = Imovel
    context_object_name = 'imovel'
    success_url = reverse_lazy('administracao:lista_imoveis')


class ImovelCreateView(CreateView):
    template_name = 'administracao/imovel/cadastraimovel.html'
    model = Imovel
    form_class = CadastraImovelForm
    success_url = reverse_lazy('administracao:lista_imoveis')


# Views da entidade Oficina
class OficinaListView(ListView):
    template_name = 'administracao/oficina/listaoficinas.html'
    model = Oficina
    context_object_name = 'oficinas'


class OficinaUpdateView(UpdateView):
    template_name = 'administracao/oficina/atualizaoficina.html'
    model = Oficina
    fields = '__all__'
    context_object_name = 'oficina'
    success_url = reverse_lazy('administracao:lista_oficinas')


class OficinaDeleteView(DeleteView):
    template_name = 'administracao/oficina/deletaoficina.html'
    model = Oficina
    context_object_name = 'oficina'
    success_url = reverse_lazy('administracao:lista_oficinas')


class OficinaCreateView(CreateView):
    template_name = 'administracao/oficina/cadastraoficina.html'
    model = Oficina
    form_class = CadastraOficinaForm
    success_url = reverse_lazy('administracao:lista_oficinas')


# Views da entidade OrdemServico
class OrdemServicoListView(ListView):
    template_name = 'administracao/ordemservico/listaordensservico.html'
    model = OrdemServico
    context_object_name = 'ordensservico'


class OrdemServicoUpdateView(UpdateView):
    template_name = 'administracao/ordemservico/atualizaordemservico.html'
    model = OrdemServico
    fields = '__all__'
    context_object_name = 'os'
    success_url = reverse_lazy('administracao:lista_os')


class OrdemServicoDeleteView(DeleteView):
    template_name = 'administracao/ordemservico/deletaordemservico.html'
    model = OrdemServico
    context_object_name = 'os'
    success_url = reverse_lazy('administracao:lista_os')


class OrdemServicoCreateView(CreateView):
    template_name = 'administracao/ordemservico/cadastraordemservico.html'
    context_object_name = 'ordem_servico'
    model = OrdemServico
    form_class = CadastraOrdemServicoForm
    success_url = reverse_lazy('administracao:lista_os')

manutask/administracao/templates/administracao/pessoa/atualizapessoa.html
<!-- Estendemos do template base -->
{% extends "administracao/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da página -->
{% block title %} Atualizar Pessoa {% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> Atualizar Pessoa </h5>
          <p class="card-text">
            <form method="post">
              {% csrf_token %}

              {{ form }}

              <button type="submit" class="btn btn-primary"> Confirma </button>
              <a href="{% url 'administracao:lista_pessoas' %}" class="btn btn-danger"> Cancelar </a>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

manutask/administracao/templates/administracao/pessoa/cadastrapessoa.html
<!-- Estendemos do template base -->
{% extends "administracao/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da página -->
{% block title %} Cadastra Pessoa {% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title"> Cadastrar Pessoa </h3>
          <p class="card-text">
            <form method="post">
              {% csrf_token %}

              {{ form }}

              <button type="submit" class="btn btn-primary"> Confirma </button>
              <a href="{% url 'administracao:lista_pessoas' %}" class="btn btn-danger"> Cancelar </a>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

manutask/administracao/templates/administracao/pessoa/deletapessoa.html
<!-- Estendemos do template base -->
{% extends "administracao/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da página -->
{% block title %} Deletar Pessoa {% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title"> Deletar Pessoa </h3>
          <p class="card-text">
            <form method="post">
              {% csrf_token %}
              <p> Você confirma a exclusão da pessoa abaixo? </p>
              <p> {{ pessoa.nome }} {{ pessoa.sobrenome }}</p>
              <p> CPF {{ pessoa.cpf }} </p>

              <button type="submit" class="btn btn-danger"> Confirma </button>
              <a href="{% url 'administracao:lista_pessoas' %}" class="btn btn-secondary"> Cancelar </a>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

manutask/administracao/templates/administracao/pessoa/listapessoas.html
<!-- Estendemos do template base -->
{% extends "administracao/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Pessoas cadastradas - Manutask{% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}
<div class="container">
  <div class="row" align="right">
    <a href="{% url 'administracao:cadastra_pessoa' %}">
      <i class="bi bi-asterisk fa-lg"></i>
    </a>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      {% for pessoa in pessoas %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> {{ pessoa.id }} : {{ pessoa.nome }} </h5>
            <p class="card-text"> {{ pessoa.nome }} {{ pessoa.sobrenome }} </p>
            <p class="card-text"> CPF: {{ pessoa.cpf }} </p>
            <a href="{% url 'administracao:atualiza_pessoa' pk=pessoa.id %}" class="btn btn-secondary"> Atualizar </a>
            <a href="{% url 'administracao:deleta_pessoa' pk=pessoa.id %}" class="btn btn-danger"> Deletar </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}